### ISSUE TITLE
findCollidingIds AssertionError exception keeps crashing the app 

### ISSUE THREAD

**Issue by DarkionAvey** [saket/Dank#4]
Hi! 
I've been using the app for couple of days now, and I must say I'm impressed, well done! But I noticed that the app crashes when scrolling very far down the list. According to logcat, it's caused by SubredditSubmissionsAdapter#findCollidingIds. 

I didn't go through the code so I just [silenced the exception in a fork](https://github.com/DarkionAvey/Dank/commit/a54460bcb96f143eebc8ba363e5eb98f79959b3c). For now I haven't faced any side effects, but have a look at the issue and possibly fix it when you have time. 

Thanks

**Comment by Tunous** [comment]
I would like to try and fix this too.
@saket is there a way for us to know the reason why you added said method in this commit:
https://github.com/saket/Dank/commit/c6b611474c76e78e2e5da043cf22d16e150e07cc ? The link added in comment doesn't work for me.

**Comment by saket** [comment]
`findCollidingIds()` throws an error if two `SubmissionRowUiModel` items in the data-set have the same IDs. In this case, the collision is happening between items of `SubredditSubmission`.

The adapterId is generated here: [JrawUtils2#L20](https://github.com/saket/Dank/blob/b429407f488a9a6e8b170fab29066e301ed4e1cb/app/src/main/java/me/saket/dank/utils/JrawUtils2.kt#L20). Fortunately or unfortunately this function is used for generating the adapter ID of multiple types of Reddit related objects. 

I'm using a combination of hashcode + created-at-time in hopes that they'll be unique, but clearly that's wrong. Multiple submissions can have the same created-at timestamp, increasing their likelihood of collision. 

@Tunous unfortunately, the Bugsnag dashboard is private so you won't be able to open the link. It doesn't have anything useful except for links to the two colliding submissions. I wonder if I can make my bugsnag dashboard public.

**Comment by DarkionAvey** [comment]
But if you read the printed logcat (using `Log.e`), `SubmissionRowUiModel`  'existing' and 'row' are basically the same entry, so the issue isn't in `findCollidingIds` but somewhere upstream where an article is retrieved twice (?)

**Comment by saket** [comment]
You're right. The rows point to the same submission. Looks like the problem lies somewhere else upstream.

**Comment by Tunous** [comment]
I've debugged the bug a bit and found that the problem lies in part of code which deals with saving new submissions to local database:

https://github.com/saket/Dank/blob/b429407f488a9a6e8b170fab29066e301ed4e1cb/app/src/main/java/me/saket/dank/ui/submission/SubmissionRepository.java#L445

The code inside of the linked if statement executes basically every time because `saveTimeMillis` is a part of primary key for `CachedSubmissionId2`. Since everything (including duplicates) fetched from the API is saved to the database we are getting id collisions.

I've [fixed](https://github.com/Tunous/Dank/commit/71404c12fe8cee3c8770287ebef5eff52c10d724) this bug by removing `saveTimeMillis` from the primary key for `CachedSubmissionId2` and adding `id` here instead which seems to be something that is supposed to uniquely identify submissions.

___

@saket are you interested in accepting pull requests to this repository or would you prefer to leave everything up to forks?

**Comment by saket** [comment]
@Tunous just an information about the bug fix is sufficient, don't bother sending back patches to Dank. As much as I'd like them, I don't think I have enough time to maintain this app anymore.

**Comment by saket** [comment]
Will be fixed with #6
